#!/bin/sh -e
# Script to dispatch NetworkManager events
#
# Runs io.elementary.capnet-assist helper on walled garden networks.
# See NetworkManager(8) for further documentation of the dispatcher events.

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

msg() {
    if [ -n "$(command -v logger)" ]; then
        logger -s -t io.elementary.capnet-assist $@ || :
    fi
}

wait_for_process() {
    local process="$1"
    # timeout after 90 seconds
    for t in $(seq 1 30); do
        [ -z "$(pgrep "$process")" ] || return
        sleep 3;
    done
}

#launch the browser, but on boot we need to wait that nm-applet starts
start_browser() {
    local user="$1"
    local display="$2"

    wait_for_process nm-applet

    export DISPLAY="$display"

    msg -p user.notice "starting browser for user: '$user', with display: '$display'"
    runuser -u "$user" -- io.elementary.capnet-assist 2>/dev/null || \
    msg -p user.err "browser failed for user: '$user', with display: '$display'"
}

[ "$2" = "connectivity-change" -a "$CONNECTIVITY_STATE" = "portal" ] || exit 0

msg -p user.debug "captive portal detected on interface: '$1'"

# Match 2nd column of who's output with ' :[at least one digit] '
who | awk '$2 ~ /:[0-9]+/ { print $1 " " $2; };' | \
while read user display; do
    start_browser "$user" "$display"
done
