#!/bin/sh

set -e

flatpak remote-add --if-not-exists --system appcenter https://flatpak.elementary.io/repo.flatpakrepo
flatpak install --system --noninteractive appcenter io.elementary.capnet-assist//stable || true

flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --system --noninteractive flathub org.freedesktop.Platform.GL.default//23.08 || true

#DEBHELPER#

exit 0
