#!/bin/sh

set -e

flatpak remote-add --if-not-exists --system appcenter https://flatpak.elementary.io/repo.flatpakrepo
flatpak install --system --noninteractive appcenter io.elementary.capnet-assist//stable || true

FILE=/etc/flatpak/freedesktop.filter
if [ ! -f "$FILE" ]; then
    mkdir -p /etc/flatpak

    cat << EOF > /etc/flatpak/freedesktop.filter
# Only allow FreeDesktop extensions
deny *
allow runtime/org.freedesktop.*
EOF
fi

flatpak remote-add --if-not-exists --system --filter=/etc/flatpak/freedesktop.filter freedesktop https://flathub.org/repo/flathub.flatpakrepo
flatpak install --system --noninteractive freedesktop org.freedesktop.Platform.GL.default//22.08 || true

#DEBHELPER#

exit 0
