name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:unstable
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libgcr-3-dev libgranite-dev libgtk-3-dev libhandy-1-dev libwebkit2gtk-4.0-dev meson valac
    - name: Build
      run: |
        meson build
        ninja -C build
        ninja -C build install

  lint:

    runs-on: ubuntu-latest
    
    container:
      image: valalang/lint
      
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
